language: node_js
node_js:
  - 10
after_success:
  - mkdir dist
  - cp -R index.html js dist
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: master